server:
  port: 8888
spring:
  application:
    name: micro-config-server
  profiles:
    active:
    - native
  cloud:
    config:
      server:
        git:
          uri: https://github.com/eltonk2k/spring-microservices/tree/master/micro-config-server/src/main/resources/config
          default-label: master
          search-paths:
          - 'config*'